apiVersion: v1
kind: Pod
metadata:
  name: emptydir-volume-test
spec:
  restartPolicy: OnFailure
  containers:
  - name: busybox
    image: busybox:stable
    command: ['sh', '-c', 'echo "$(uname -a)" > /data/data.txt; cat /data/data.txt']
    volumeMounts:
      - mountPath: /data/
        name: emptydir-volume
  volumes:
  - name: emptydir-volume
    emptyDir: {}


